//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppTesoreria
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaEmpleadosNomina
    {
        public int Id { get; set; }
        public string RNC { get; set; }
        public string Tipo { get; set; }
        public string Cedula { get; set; }
        public decimal SueldoBruto { get; set; }
        public string TipoMoneda { get; set; }
        public decimal ARS { get; set; }
        public decimal AFP { get; set; }
        public decimal SueldoNeto { get; set; }
    }
}
